### ISSUE TITLE
Eww bar styles not working properly

### ISSUE THREAD

**Issue by tims233** [AlphaTechnolog/dotfiles-v2#1]
Some colors in the bars are not displaying properly ,i tried to find the problem but i didn't knew much sass so couldn't. I also tried to find the cause using eww inspector but couldn't figure it out, my bar:

![2022-06-09_13-58](https://user-images.githubusercontent.com/70734894/172868650-013cc5b2-43e1-4c41-bc33-08cd9cd3a5b1.png)

**Comment by AlphaTechnolog** [comment]
what, do you installed the latest dotfiles version? i think i fixed this, it's a problem with gtk

**Comment by AlphaTechnolog** [comment]
if you think you updated the repo, could you share me the content of `~/.config/eww/eww.scss` i think i added:

```css
* {
  all: unset;
}
```

That will fix the problem

> Another note: if the problem persists, please could you give me the name of your gtk theme please?

**Comment by tims233** [comment]
i did installed the latest version but there was not that line in my eww.scss,after i added that line it seemed to fixed it,
thanks a lot

**Comment by AlphaTechnolog** [comment]
This is extraneous, well but no problem mate, now enjoy with this bspwm config, i hope you like it! 😁
