### ISSUE TITLE
issue in the config

### ISSUE THREAD

**Issue by 0x4c554c5a** [AlphaTechnolog/dotfiles-v2#10]
So I'm on arch linux, I followed every step as mentioned and when I switch to awesomewm I get the following errors:
"error while running function!
stack traceback:
	[C]: in function 'require'
	/home/lulz/.config/awesome/helpers.lua:10: in main chunk
	[C]: in function 'require'
	/home/lulz/.config/awesome/signal/volume.lua:8: in main chunk
	[C]: in function 'require'
	/home/lulz/.config/awesome/signal/global.lua:1: in main chunk
	[C]: in function 'require'
	/home/lulz/.config/awesome/rc.lua:5: in main chunk
error: /home/lulz/.config/awesome/helpers.lua:10: module 'modules.rubato' not found:
	no field package.preload['modules.rubato']
	no file '/usr/share/lua/5.4/modules/rubato.lua'
	no file '/usr/share/lua/5.4/modules/rubato/init.lua'
	no file '/usr/lib/lua/5.4/modules/rubato.lua'
	no file '/usr/lib/lua/5.4/modules/rubato/init.lua'
	no file './modules/rubato.lua'
	no file './modules/rubato/init.lua'
	no file '/home/lulz/.config/awesome/modules/rubato.lua'
	no file '/home/lulz/.config/awesome/modules/rubato/init.lua'
	no file '/root/.config/awesome/modules/rubato.lua'
	no file '/root/.config/awesome/modules/rubato/init.lua'
	no file '/etc/xdg/awesome/modules/rubato.lua'
	no file '/etc/xdg/awesome/modules/rubato/init.lua'
	no file '/usr/share/awesome/lib/modules/rubato.lua'
	no file '/usr/share/awesome/lib/modules/rubato/init.lua'
	no file '/usr/lib/lua/5.4/modules/rubato.so'
	no file '/usr/lib/lua/5.4/loadall.so'
	no file './modules/rubato.so'
	no file '/home/lulz/.config/awesome/modules/rubato.so'
	no file '/root/.config/awesome/modules/rubato.so'
	no file '/etc/xdg/awesome/modules/rubato.so'
	no file '/usr/share/awesome/lib/modules/rubato.so'
	no file '/usr/lib/lua/5.4/modules.so'
	no file '/usr/lib/lua/5.4/loadall.so'
	no file './modules.so'
	no file '/home/lulz/.config/awesome/modules.so'
	no file '/root/.config/awesome/modules.so'
	no file '/etc/xdg/awesome/modules.so'
	no file '/usr/share/awesome/lib/modules.so'
2022-10-15 12:09:50 W: awesome: `awful.layout.layouts` was set before `request::default_layouts` could be called. Please use `awful.layout.append_default_layouts` to  avoid this problem"

**Comment by AlphaTechnolog** [comment]
that was fixed yesterday, that happens when submodules wasn't cloned (and because the missconfiguration, them wasn't able to be cloned), follow the new instructions to clone the repository
