### ISSUE TITLE
An error Happened -  attemp to compare number with nil

### ISSUE THREAD

**Issue by juanda3132** [AlphaTechnolog/dotfiles-v2#12]
Hello, good configuration, everything is fine except for this warning that comes up all the time, I don't know what it is due to, can you help me. 
![image](https://user-images.githubusercontent.com/75529640/204071250-5a9e07fe-da07-4c97-881b-a1ef24f5b90a.png)
Thank you

**Comment by AlphaTechnolog** [comment]
Hello! Glad to hear that you're liking and enjoying this configuration! Maybe this could be a dependency problem (that possibly i forgot to add), can you tell me if this happens on awesomew-vertical-version or awesome-horizontal one? pls

**Comment by juanda3132** [comment]
that happened in the awesome vertical version

**Comment by AlphaTechnolog** [comment]
Ok so yeah, looks like a dependency that I forgot to add, you can try manually executing the scripts inside the scripts folder and check if some of them throws some error(s). Also judging by the error, looks like an error inside the charts scripts, like the CPU, ram, temperature, etc

**Comment by AlphaTechnolog** [comment]
What shell do you have set as default one?

**Comment by AlphaTechnolog** [comment]
That could happen with shells like fish because it will execute some bash-scripts with fish instead of bash... So I could try to get it working without the default shell and use bash everytime

**Comment by AlphaTechnolog** [comment]
closing in favor of #14 and because of inactivity
