### ISSUE TITLE
Disabling notification for media

### ISSUE THREAD

**Issue by Underscore30** [AlphaTechnolog/dotfiles-v2#17]
Any way to disable the notification for media that pops up when watching a video or music? The notification is useful for system stuff but it can get quite annoying for media so I'm wondering if there's any way to disable it.

**Comment by AlphaTechnolog** [comment]
just comment this [line](https://github.com/AlphaTechnolog/dotfiles/blob/2486588d5cdb01f29426177b28f5e432532c0135/cfg/awesome/configuration/init.lua#L9)
