### ISSUE TITLE
some applications open with a disproportionate size and without respecting the layout tile in awesomewm verical

### ISSUE THREAD

**Issue by JupitX** [AlphaTechnolog/dotfiles-v2#18]
Hi, all is fine, I'm resolving all issues on my own but i can't resolve that one. When I run Firefox with keybinding or not, it opens with different size and all the other issues in the tittle, here an image...
![screenshot-CO0SNk](https://user-images.githubusercontent.com/109345723/210154098-1647a879-0ed7-4f65-8793-a203c0765d13.png)
I know it's all black too but it have a little space between the bar and the Firefox window and it doesn't respect it.

**Comment by JefHern** [comment]
> Hi, all is fine, I'm resolving all issues on my own but i can't resolve that one. When I run Firefox with keybinding or not, it opens with different size and all the other issues in the tittle, here an image... ![screenshot-CO0SNk](https://user-images.githubusercontent.com/109345723/210154098-1647a879-0ed7-4f65-8793-a203c0765d13.png) I know it's all black too but it have a little space between the bar and the Firefox window and it doesn't respect it.

**Comment by JupitX** [comment]
It was maximized, im very, very stupid
