### ISSUE TITLE
Doas: Operation not permitted

### ISSUE THREAD

**Issue by Vespulaz** [AlphaTechnolog/dotfiles-v2#2]
I configured all the commands below
![image](https://user-images.githubusercontent.com/84973401/187008583-93009c47-cbf3-4cd4-97a6-642693f7cf58.png)
But when I use `doas touch /hello`, doas says **Operation not permitted**
![image](https://user-images.githubusercontent.com/84973401/187008704-4bd1619a-8b9e-4265-9108-27351d0a65b7.png)

I'm currently using Arch Linux btw

**Comment by AlphaTechnolog** [comment]
You have to be inside the group `wheel` to avoid some errors. Are u in that group? If not, run this: `sudo usermod -aG wheel $(whoami)`

**Comment by Vespulaz** [comment]
Oh, it worked for me. Thanks for the support!
