### ISSUE TITLE
How to open minimized windows?

### ISSUE THREAD

**Issue by f3nix-12** [AlphaTechnolog/dotfiles-v2#20]
Whenever I switch to different workspace while gaming the game gets minimized and I can't find a way to get back to it, I also cannot get back to the windows I minimize from the titlebar, how do I get to the minimized windows? Sorry for the noob question.

**Comment by AlphaTechnolog** [comment]
Hey, hello, no problem, you can try by using `mod + ctrl + n` to reopen minimized windows

**Comment by f3nix-12** [comment]
Hey, thanks for the quick reply, mod + ctrl + n didn't work for the vertical awesomewm version however I managed to get it working by copying the keybindings for restore minimized from the horizontal awesomewm version ✌️

**Comment by AlphaTechnolog** [comment]
Ohh, then i forgot to do it in the vertical one too, glad to hear that you solved the issue, marking this as closed since i see you have resolved.
