### ISSUE TITLE
Awesome Horizontal: How to move bar to top?

### ISSUE THREAD

**Issue by hamensman** [AlphaTechnolog/dotfiles-v2#24]
How do i move the bar from the bottom to the top?

**Comment by hamensman** [comment]
Never mind. It's in `awesome/ui/bar/init.lua`.

**Comment by hamensman** [comment]
When I do that (`position = 'top'`), all the widgets are obviously still displaying from the bottom. Is there an easy way to bring them all up?

**Comment by AlphaTechnolog** [comment]
yeah you will need to check out every widget in the bar and change those vertical orientations to the horizontal ones, some ones like taglists and those kind of widgets wouldn't require too much effort as they already have the position thingy in some Lua table, but for some others widgets which are kinda more complex you'll require some work, anyways if u find a widget that you don't know how to make it look horizontal, feel free to ask and I'll try to help
