### ISSUE TITLE
Awesome Horizontal: Change application icon theme

### ISSUE THREAD

**Issue by hamensman** [AlphaTechnolog/dotfiles-v2#25]
If I understand correctly, the icon theme your using for the application icons is `decay-icons`? If so, how can I change it to, say, `Papirus`?

**Comment by AlphaTechnolog** [comment]
Im using the bling icon helpers (if i recall correctly), so if you change your system icons using things like lxappearance and such things (please check that it changed the icons theme at the ~/.gtkrc and ~/.config/gtk-3*/settings* files), it should change the icon on AwesomeWM after a WM reload.

**Comment by hamensman** [comment]
So that means `awesome/bling/helpers/icon_theme.lua`  _should_ pick the icon theme chosen in lxappearance, right? I'm not getting that unfortunately.

I have to do a bad workound by writing a file `awesome/gtk-icons.lua` and importing that in `awesome/rc.lua`:
```lua
local menubar = require("menubar")
local gears = require("gears")

client.connect_signal("manage", function(c)
    local icon_theme = "Papirus-Dark"
    local icon = gears.surface(string.format("/usr/share/icons/%s/48x48/apps/%s.svg", icon_theme, c.instance))
    c.icon = icon._native
    icon:finish()
end)
```
```lua
pcall(require, "luarocks.loader")

require "awful.autofocus"

require "signal.global"
require "user_likes"
require "autostart"
require "configuration"
require "ui"
require "gtk-icons
```
Btw, I know zero lua.

**Comment by AlphaTechnolog** [comment]
well, assuming that this one is the horizontal awesomewm rice, after seeing the code of it, im seeing that im using awful.widget.tasklist, with no support for gtk icons but the default icons pack. so yeah that workarounds works great for now, which actually replaces the icon property of each app letting the tasklist render it successfully
