### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by HoangLoi2031** [AlphaTechnolog/dotfiles-v2#27]
Hi,
I am running awesomewm on Debian. I followed the steps in the install instructions, but when I login to awesome I get the following error message:

error while running function!
stack traceback:
/home/sharpe/.config/awesome/configuration/mousebindings.lua:5 in local 'set_mousebindings'
/home/sharpe/.config/awesome/configuration/mousebindings.lua:26: in main chunk
[C]: in function 'require'
/home/sharpe/.config/awesome/configuration/init.lua:3: in main chunk
[C]: in function 'require'
/home/sharpe/.config/awesome/rc.lua:8: in main chunk
error: /home/sharpe/.config/awesome/configuration/mousebindings.lua:5: attempt to call a nil value (field 'append_global_mousebindings')

How to fix it ?

**Comment by AlphaTechnolog** [comment]
it seems to be that you don't have installed the git version of AwesomeWM, how did u install awesomewm? through apt?

**Comment by HoangLoi2031** [comment]
> it seems to be that you don't have installed the git version of AwesomeWM, how did u install awesomewm? through apt?

yeah i downloaded it from apt

**Comment by AlphaTechnolog** [comment]
well yeah apt iirc installs the stable version of awesome , to install the
git version of it, please take a look on compiling awesomewm from source in
their source code repository at GitHub, https://github.com/awesomewm/awesome,
also remember to uninstall awesome from apt before doing the compilation

**Comment by HoangLoi2031** [comment]
can i download deb package from source
