### ISSUE TITLE
file or directory not found after make clean install

### ISSUE THREAD

**Issue by GerardPolloRebozado** [AlphaTechnolog/dotfiles-v2#4]
Im in ArchLinux with awesomewm
after making sudo make clean install i get and error

`sudo make clean install
[sudo] contraseña para gerard:
rm -f st config.h st.o x.o boxdraw.o hb.o st-0.8.4.tar.gz *.o *.orig *.rej
cp config.def.h config.h
gcc -I/usr/X11R6/include  `pkg-config --cflags fontconfig`  `pkg-config --cflags freetype2`  `pkg-config --cflags harfbuzz` -DVERSION=\"0.8.4\" -DICON=\"/usr/local/share/pixmaps/st.png\" -D_XOPEN_SOURCE=600  -O1 -c st.c
En el fichero incluido desde st.c:21:
st.h:6:10: error fatal: gd.h: No existe el fichero o el directorio
    6 | #include <gd.h>
      |          ^~~~~~
compilación terminada.
make: *** [Makefile:22: st.o] Error 1`

**Comment by AlphaTechnolog** [comment]
Oops, i miss one pkg then, for arch install the PKG gd

**Comment by AlphaTechnolog** [comment]
Then rerun the command

**Comment by GerardPolloRebozado** [comment]
Yes now its working :)

**Comment by GerardPolloRebozado** [comment]
> Yes now its working :)

Im having a problem with the Fonts cause the pacman icons of the bottom bar are not showing correctly. I have both Jetbrains fotns and material icons installed.

**Comment by AlphaTechnolog** [comment]
Hm, that is strange, can you show me the output of the command: `fc-list | grep Material`?

**Comment by GerardPolloRebozado** [comment]
> fc-list | grep Material

Sure here is it


[gerard@archlinux ~]$ fc-list | grep Material
/home/gerard/.local/share/fonts/MaterialIcons/MaterialIconsSharp-Regular.otf: Material Icons Sharp:style=Regular
/home/gerard/.local/share/fonts/MaterialIcons/MaterialIconsOutlined-Regular.otf: Material Icons Outlined:style=Regular
/home/gerard/.local/share/fonts/Material.ttf: Material:style=Regular
/home/gerard/.local/share/fonts/material-design-icons.ttf: Material Icons:style=Regular
/home/gerard/.local/share/fonts/MaterialIcons/MaterialIcons-Regular.ttf: Material Icons:style=Regular
/home/gerard/.local/share/fonts/MaterialIcons/MaterialIconsRound-Regular.otf: Material Icons Round:style=Regular
/home/gerard/.local/share/fonts/MaterialIcons-Regular.ttf: Material Icons:style=Regular
/usr/local/share/fonts/material-design-icons.ttf: Material Icons:style=Regular
/home/gerard/.local/share/fonts/materialdesignicons-webfont (1).woff: Material Design Icons:style=Regular
/home/gerard/.local/share/fonts/MaterialIcons/MaterialIconsTwoTone-Regular.otf: Material Icons Two Tone:style=Regular
[gerard@archlinux ~]$

**Comment by AlphaTechnolog** [comment]
well, in fact, it's really strange, i'll need to try to reproduce it then
> can you open another issue attaching an image showing how the desktop looks please? like how looks the pacman-taglist, i'll try to reproduce
